#!/bin/bash

if [ -z "$1" ]; then
  echo "Please provide a 4-digit integer as input."
  exit 1
fi

input=$1

hash=$(echo -n "$input" | sha256sum | awk '{print $1}')

echo "$hash" >> hash_output.txt


